#ifndef ERRORCODE_H
#define ERRORCODE_H

#define FILE_IS_NULL_CODE 601
#define SUCCESS_LOAD_ADMIN_FILE_CODE 200
#define SUCCESS_SAVE_ADMIN_CODE 201
#define SUCCESS_LOAD_STUDENT_CODE 202
#define  SUCCESS_SAVE_STUDENT_CODE 203

#endif // ERRORCODE_H
